
#pragma once

#include <ConfigCustomGUIImpl.h>

class ATL_NO_VTABLE CConfigGUIItemDlg :
	public CCustomConfigWndImpl<CConfigGUIItemDlg>,
	public CDialogResize<CConfigGUIItemDlg>
{
public:
	enum { IDD = IDD_CONFIGGUI_ITEM };

	BEGIN_MSG_MAP(CConfigGUIItemDlg)
		CHAIN_MSG_MAP(CDialogResize<CConfigGUIItemDlg>)
		CHAIN_MSG_MAP(CCustomConfigWndImpl<CConfigGUIItemDlg>)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
	END_MSG_MAP()

	BEGIN_DLGRESIZE_MAP(CConfigGUIItemDlg)
		DLGRESIZE_CONTROL(IDC_CG_OPERATION, DLSZ_SIZE_X)
		DLGRESIZE_CONTROL(IDC_CG_OPCONFIG, DLSZ_SIZE_X|DLSZ_SIZE_Y)
		DLGRESIZE_CONTROL(IDC_CG_ID, DLSZ_DIVSIZE_X(3))
		DLGRESIZE_CONTROL(IDC_CG_NAMELABEL, DLSZ_DIVMOVE_X(3))
		DLGRESIZE_CONTROL(IDC_CG_NAME, DLSZ_DIVMOVE_X(3)|DLSZ_MULDIVSIZE_X(2, 3))
		DLGRESIZE_CONTROL(IDC_CG_HIDDEN, DLSZ_MOVE_X)
	END_DLGRESIZE_MAP()

	BEGIN_CONFIGITEM_MAP(CConfigGUIItemDlg)
		CONFIGITEM_EDITBOX(IDC_CG_ID, CFGID_TOOLBAR_ID)
		CONFIGITEM_EDITBOX(IDC_CG_NAME, CFGID_TOOLBAR_NAME)
		CONFIGITEM_COMBOBOX(IDC_CG_OPERATION, CFGID_TOOLBAR_COMMANDS)
		CONFIGITEM_CHECKBOX(IDC_CG_HIDDEN, CFGID_TOOLBAR_HIDDEN)
		CONFIGITEM_SUBCONFIG(IDC_CG_OPCONFIG, CFGID_TOOLBAR_COMMANDS)
	END_CONFIGITEM_MAP()

	LRESULT OnInitDialog(UINT UNREF(a_uMsg), WPARAM UNREF(a_wParam), LPARAM UNREF(a_lParam), BOOL& a_bHandled)
	{
		DlgResize_Init(false, false, 0);

		return 1;
	}
};
