
#pragma once

#include <ConfigCustomGUIList.h>

class ATL_NO_VTABLE CConfigGUIToolbarDlg :
	public CCustomConfigWndImpl<CConfigGUIToolbarDlg>,
	public CCustomConfigGUIList<CConfigGUIToolbarDlg, IDC_CG_LIST, IDC_CG_TOOLBAR, IDC_CG_ITEM, IDS_CGTOOLBAR_BUTTONNAMES, 0, 0, CCGUILIST_DEFAULTICON, CCGUILIST_DEFAULTICON, CCGUILIST_DEFAULTICON, 0, CCGUILIST_DEFAULTICON, CCGUILIST_DEFAULTICON>,
	public CDialogResize<CConfigGUIToolbarDlg>
{
public:
	CConfigGUIToolbarDlg() :
		CCustomConfigGUIList<CConfigGUIToolbarDlg, IDC_CG_LIST, IDC_CG_TOOLBAR, IDC_CG_ITEM, IDS_CGTOOLBAR_BUTTONNAMES, 0, 0, CCGUILIST_DEFAULTICON, CCGUILIST_DEFAULTICON, CCGUILIST_DEFAULTICON, 0, CCGUILIST_DEFAULTICON, CCGUILIST_DEFAULTICON>(CFGID_TOOLBAR_ITEMS)
	{
	}
	enum { IDD = IDD_CONFIGGUI_TOOLBAR };

	BEGIN_MSG_MAP(CConfigGUIToolbarDlg)
		CHAIN_MSG_MAP(CDialogResize<CConfigGUIToolbarDlg>)
		CHAIN_MSG_MAP(CCustomConfigWndImpl<CConfigGUIToolbarDlg>)
		CHAIN_MSG_MAP(ListClass)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
	END_MSG_MAP()

	BEGIN_DLGRESIZE_MAP(CConfigGUIToolbarDlg)
		DLGRESIZE_CONTROL(IDC_CG_LIST, DLSZ_DIVSIZE_Y(2))
		DLGRESIZE_CONTROL(IDC_CG_ITEM, DLSZ_SIZE_X|DLSZ_DIVSIZE_Y(2))
		DLGRESIZE_CONTROL(IDC_CG_VIEWLABEL, DLSZ_DIVMOVE_Y(2))
		DLGRESIZE_CONTROL(IDC_CG_VIEW, DLSZ_SIZE_X|DLSZ_DIVMOVE_Y(2))
		DLGRESIZE_CONTROL(IDC_CG_VIEWCONFIG, DLSZ_SIZE_X|DLSZ_DIVMOVE_Y(2)|DLSZ_DIVSIZE_Y(2))
	END_DLGRESIZE_MAP()

	BEGIN_CONFIGITEM_MAP(CConfigGUIToolbarDlg)
		CONFIGITEM_COMBOBOX(IDC_CG_VIEW, CFGID_TOOLBAR_VIEW)
		CONFIGITEM_SUBCONFIG(IDC_CG_VIEWCONFIG, CFGID_TOOLBAR_VIEW)
	END_CONFIGITEM_MAP()

	LRESULT OnInitDialog(UINT UNREF(a_uMsg), WPARAM UNREF(a_wParam), LPARAM UNREF(a_lParam), BOOL& a_bHandled)
	{
		DlgResize_Init(false, false, 0);

		return 1;
	}

	void ExtraConfigNotify()
	{
		UpdateList();
	}
};
