//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RWDesignerCore.rc
//
#define IDS_PROJNAME                    100
#define IDD_NEWFILEDLG                  108
#define IDD_RECENTFILEDLG               111
#define IDS_GENERICERROR                124
#define IDS_STARTPAGEONLINE_NAME        126
#define IDS_STARTPAGEONLINE_DESC        127
#define IDR_MAINFRAME                   128
#define IDS_ERROR_OPERATION             129
#define IDS_ERROR_CREATION              130
#define IDS_LANGUAGE                    131
#define IDS_VIEWCREATIONFAIL            132
#define IDS_STARTVIEW_TOOLS             133
#define IDS_RECENTFILES_TOOLBAR         133
#define IDS_DOCUMENTNAMETEMPL           134
#define IDS_STARTVIEWBTN_NEW            135
#define IDS_STARTVIEWBTN_OPEN           136
#define IDS_STARTVIEWBTN_RECENT         137
#define IDS_STARTVIEWBTN_TUTOR          138
#define IDS_FORCEOPENAS                 138
#define IDS_SAVECHANGESTO               139
#define IDS_ACTIONFAILED                140
#define IDS_STARTVIEW_UNKNOWNCATEGORY   141
#define IDS_SAVEDLGCAPTION              142
#define IDS_ERROR_SAVE                  143
#define IDS_STARTPAGENEWDOCUMENT_NAME   144
#define IDS_STARTPAGENEWDOCUMENT_DESC   145
#define IDS_STARTPAGEOPENFILE_NAME      146
#define IDS_STARTPAGEOPENFILE_DESC      147
#define IDS_STARTPAGERECENTFILES_NAME   148
#define IDS_STARTPAGERECENTFILES_DESC   149
#define IDS_DROPMSG_ADDCOMMANDS         150
#define IDS_DROPMSG_OPENFILES           151
#define IDS_GCNAME_MAINFRAME            152
#define IDS_GCDESC_MAINFRAME            153
#define IDS_CFGID_CTXHELPASTIPS_NAME    154
#define IDS_CFGID_CTXHELPASTIPS_DESC    155
#define IDS_SAVECHANGES_YES             156
#define IDS_SAVECHANGES_NO              157
#define IDS_SAVECHANGES_CANCEL          158
#define IDS_SAVECHANGES_CONTENT         159
#define IDS_RECENTFILES_COLNOTE         160
#define IDS_CONFIGURETOOLBAR            161
#define IDS_MN_HELP_DONATE              162
#define IDS_MD_HELP_DONATE              163
#define IDS_MN_HELP_REGISTER            164
#define IDS_MD_HELP_REGISTER            165
#define IDS_MN_HELP_BETA                166
#define IDS_MD_HELP_BETA                167
#define IDS_CONFIGUREWINDOW             168
#define IDS_RECENTFILES_COLNAME         192
#define IDS_RECENTFILES_COLPATH         193
#define IDS_RECENTFILES_COLTYPE         194
#define IDS_RECENTFILES_COLSIZE         195
#define IDS_RECENTFILES_COLDATEMOD      196
#define IDS_MENU_ABOUTAPPLICATION       199
#define IDS_FILELEN_BYTES               200
#define IDD_CONFIGURELAYOUT             201
#define IDS_FILELEN_KBYTES              201
#define IDC_NEWDOC_NAME                 202
#define IDS_FILELEN_MBYTES              202
#define IDC_NEWDOC_NAMETEXT             203
#define IDS_FILEDATE_MODIFIED           203
#define IDS_NORECENTFILES               204
#define IDD_CONFIGGUI_LAYOUT            205
#define ID_LAYOUT_MANAGE                206
#define IDD_CONFIGFRAME                 207
#define IDC_RECFILE_USELAYOUT           208
#define IDD_MANAGECONFIGURABLEITEMS     208
#define IDC_APPOPT_SHOWTUTORIALS        209
#define IDD_FATALERROR                  209
#define IDC_CG_VIEW                     209
#define IDC_CG_OPERATION                209
#define ID_LAYOUT_CONFIGURECURRENT      210
#define IDC_CGLAYOUT_VIEW               210
#define IDR_TUTORIAL1                   210
#define IDC_CG_VIEWCONFIG               210
#define IDC_CG_OPCONFIG                 210
#define IDC_CGLAYOUTTAB_FRAME           212
#define IDC_CGLAYOUT_FRAME              212
#define IDC_CG_TOOLBAR                  214
#define ID_MNGLTS_DELETE                215
#define IDC_CG_LIST                     215
#define ID_MNGLTS_CREATE                216
#define IDC_CG_ITEM                     216
#define ID_MNGLTS_MOVEUP                217
#define ID_MNGLTS_MOVEDOWN              218
#define ID_MNGLTS_RENAME                219
#define ID_MNGLTS_CONFIGURE             220
#define ID_MNGLTS_CLONE                 221
#define IDC_CUSTOM1                     221
#define ID_MNGOPS_DELETE                222
#define IDC_MANAGE_ITEMLIST             222
#define ID_LAYOUT_SAVECURRENTAS         223
#define IDC_MANAGE_LABEL                223
#define ID_MNGOPS_CREATE                224
#define IDC_APPOPT_UNDOMODE_GRP         224
#define ID_MNGOPS_MOVEUP                225
#define ID_STRTDLG_NEW                  225
#define IDC_APPOPT_UNDODEFAULT          225
#define ID_MNGOPS_MOVEDOWN              226
#define IDC_APPOPT_UNDODISABLE          226
#define IDR_OFFLINE0409                 226
#define ID_MNGOPS_RENAME                227
#define IDC_APPOPT_UNDOSINGLE           227
#define ID_HELP_CONTENTS                228
#define IDC_APPOPT_UNDOMULTIPLE         228
#define ID_MNGOPS_CONFIGURE             229
#define IDC_APPOPT_UNDOALL              229
#define IDI_ICON1                       229
#define ID_HELP_SEARCH                  230
#define IDC_BUTTON1                     230
#define IDC_FE_SAVEBUTTON               230
#define ID_HELP_ABOUT                   231
#define IDC_FE_ICON                     231
#define ID_MNGOPS_CLONE                 232
#define IDC_FE_SAVELABEL                232
#define IDS_MNGLTS_BUTTONTOOLTIPS       233
#define IDC_CGLAYOUT_ICONLABEL          233
#define IDS_MNGOPS_BUTTONTOOLTIPS       234
#define IDC_CGLAYOUT_ICON               234
#define IDS_CGTOOLBAR_BUTTONNAMES       235
#define IDC_HELP_VERTSEP                237
#define ID_TOOLS_OPTIONS                238
#define ID_TOOLS_SAVECONFIGURATIONNOW   239
#define ID_TOOLS_CONFIGUREALL           240
#define IDI_ICON2                       241
#define ID_TOOLS_SHELLASSOCIATIONS      242
#define IDC_APPOPT_STARTPAGE            242
#define IDR_DEFAULTMENU                 242
#define IDD_CONFIGGUI_TOOLBAR           243
#define IDC_CG_VIEWLABEL                243
#define IDC_CG_ID                       244
#define IDD_CONFIGGUI_ITEM              245
#define IDC_CG_NAME                     245
#define ID_DOCUMENT_MANAGEOPERATIONS    246
#define IDC_CGLAYOUT_VIEWCFG            246
#define IDC_CGLAYOUT_VIEWLABEL          247
#define IDC_CGLAYOUT_CMDSCFG            248
#define IDD_APPOPTIONS                  249
#define IDC_COMBO1                      249
#define IDC_CGLAYOUT_COMMANDS           249
#define IDC_APPOPT_INTERFACE            249
#define IDC_CGLAYOUT_COMMANDSLABEL      250
#define IDC_LS_SAVE                     251
#define IDC_APPOPT_CAPTION_GRP          252
#define IDD_GLOBALOPTIONS               254
#define IDD_CONFIGGUI_MAINFRAME         255
#define IDS_DVNULL_NAME                 256
#define IDS_OP_OPENINSAMEWINDOW         257
#define IDC_APPOPT_CAPTNAME             257
#define ID_TOOLS_CREATETEMPLATE         258
#define IDS_VIEWTOOLBAR_NAME            258
#define IDC_APPOPT_CAPTTYPE             258
#define IDB_PNG1                        258
#define IDB_WATERMARK                   258
#define IDS_MENUTOOLBAR_NAME            259
#define IDC_APPOPT_CAPTLAYOUT           259
#define IDS_MENUTOOLBAR_CMDDESC         260
#define IDC_APPOPT_CAPTAPP              260
#define IDC_CG_HIDDEN                   261
#define IDC_CG_NAMELABEL                262
#define IDC_APPOPT_LAYOUTCMDS           263
#define IDC_GO_INFO                     264
#define IDC_GO_HINT                     265
#define IDC_GO_SEP                      266
#define IDC_GO_TAB                      267
#define IDC_GO_CONFIG                   268
#define IDC_APPOPT_TOOLTIPS             269
#define IDC_PANEL                       270
#define IDC_CGLAYOUT_NAME_LABEL         271
#define IDS_CFGID_DESIGNERVIEW_NAME     272
#define IDC_CGLAYOUT_NAME               272
#define IDS_CFGID_DESIGNERVIEW_HELP     273
#define IDC_CGLAYOUT_VERB_LABEL         273
#define IDC_EDIT2                       274
#define IDC_CGLAYOUT_VERB               274
#define IDC_CGLAYOUT_DOCTYPE            275
#define IDC_CGLAYOUT_DOCTYPE_LABEL      276
#define IDC_APPOPT_DISABLEUPDATES       278
#define IDC_RECENT_HORSEP               279
#define IDC_APPOPT_CAPTPROPS            280
#define IDC_SEPLINE                     281
#define IDC_FILL                        282
#define IDS_CFGID_WIN_X_POS             512
#define IDS_CFGID_WIN_Y_POS             513
#define IDS_CFGID_WIN_WIDTH             514
#define IDS_CFGID_WIN_HEIGHT            515
#define IDS_CFGID_WIN_MAXIMIZED         516
#define IDS_CFGID_TOOL2_LINE            517
#define IDS_CFGID_LAYOUTCOMMANDS_NAME   517
#define IDS_CFGID_TOOL1_LINE            518
#define IDS_CFGID_LAYOUTCOMMANDS_DESC   518
#define IDS_CFGID_TOOL1_POS             519
#define IDS_CFGID_TOOL2_POS             520
#define IDS_CFGID_MENU_LINE             521
#define IDS_CFGID_MENU_POS              522
#define IDS_CFGID_TOOL1                 523
#define IDS_CFGID_STATUSBAR             524
#define IDS_CFGID_VIEWPROFILES_NAME     525
#define IDS_CFGID_VIEWPROFILES_DESC     526
#define IDS_STARTDLG_X                  527
#define IDS_STARTDLG_Y                  528
#define IDS_STARTDLG_WIDTH              529
#define IDS_STARTDLG_HEIGHT             530
#define IDS_RECENTFILES_NAME            531
#define IDS_RECENTFILES_HELP            532
#define IDS_CFGID_COMMANDS_NAME         533
#define IDS_CFGID_COMMANDS_DESC         534
#define IDS_CFGID_EXEC_NAME_NAME        535
#define IDS_CFGID_EXEC_NAME_DESC        536
#define IDS_CFGID_EXEC_DESC_NAME        537
#define IDS_CFGID_EXEC_DESC_DESC        538
#define IDS_CFGID_EXEC_COMMAND_NAME     539
#define IDS_CFGID_EXEC_COMMAND_DESC     540
#define IDS_CFGID_APPASKTOSAVE_NAME     541
#define IDS_CFGID_APPASKTOSAVE_DESC     542
#define IDS_CFGID_LANGUAGECODE_NAME     543
#define IDS_CFGID_USERINTERFACE_NAME    543
#define IDS_CFGID_LANGUAGECODE_DESC     544
#define IDS_CFGID_USERINTERFACE_DESC    544
#define IDS_CFGID_STARTPAGE_NAME        545
#define IDS_CFGID_STARTPAGE_DESC        546
#define IDS_CFGID_ICONID_NAME           547
#define IDS_CFGID_ICONID_DESC           548
#define IDS_CFGID_DLGS_SIZE_NAME        549
#define IDS_CFGID_DLGS_SIZE_DESC        550
#define IDS_CFGID_UNDOMODE_NAME         551
#define IDS_CFGID_UNDOMODE_DESC         552
#define IDS_CFGVAL_UNDOMODE_DEFAULT     553
#define IDS_CFGVAL_UNDOMODE_DISABLED    554
#define IDS_CFGVAL_UNDOMODE_SINGLE      555
#define IDS_CFGVAL_UNDOMODE_MULTIPLE    556
#define IDS_CFGVAL_UNDOMODE_ALL         557
#define IDS_CFGID_HELPTOPIC_NAME        558
#define IDS_CFGID_HELPTOPIC_DESC        559
#define IDS_CFGID_TOOLBAR_COMMANDS_NAME 560
#define IDS_CFGID_TOOLBAR_COMMANDS_DESC 561
#define IDS_CFGID_TOOLBAR_NAME_NAME     562
#define IDS_CFGID_TOOLBAR_NAME_DESC     563
#define IDS_CFGID_TOOLBAR_ID_NAME       564
#define IDS_CFGID_TOOLBAR_ID_DESC       565
#define IDS_CFGID_TOOLBAR_ITEMS_NAME    566
#define IDS_CFGID_TOOLBAR_ITEMS_DESC    567
#define IDS_CFGID_TOOLBAR_VIEW_NAME     568
#define IDS_CFGID_TOOLBAR_VIEW_DESC     569
#define IDS_CFGID_TOOLBAR_NAME_MENUDESC 570
#define IDS_CFGID_EXEC_PARAMS_NAME      571
#define IDS_CFGID_EXEC_PARAMS_DESC      572
#define IDS_CFGID_CAPTION_NAME          573
#define IDS_CFGID_CAPTION_DESC          574
#define IDS_CFGID_TOOLBAR_HIDDEN_NAME   575
#define IDS_CFGID_TOOLBAR_HIDDEN_DESC   576
#define IDS_CFGID_APPSAVELAYOUT_NAME    577
#define IDS_CFGID_APPSAVELAYOUT_DESC    578
#define IDS_CFGVAL_UI_MSDI              579
#define IDS_CFGVAL_UI_TABS              580
#define IDC_MANAGE_PROFILELIST          1003
#define IDC_LIST                        1017
#define IDC_IMAGE                       1019
#define IDC_TEXT                        1020
#define IDC_MANAGE_TOOLBAR              1022
#define IDC_LS_NAME                     1023
#define IDS_NEWLAYOUT                   1024
#define IDS_CLONEDVIEWPROFILE           1025
#define IDS_NEWOPERATION                1026
#define IDS_LAYOUTCFG_COLVIEW           1027
#define IDS_LAYOUTCFG_COLOPS            1028
#define IDS_CONFIGURELAYOUT             1029
#define IDC_APPOPT_LASTLAYOUT           1029
#define IDC_APPOPT_ASKTOSAVE            1030
#define IDS_CONFIGURECURRENTLAYOUT      1030
#define IDC_APPOPT_LANGUAGE             1031
#define IDS_MANAGELAYOUTS_CAPTION       1031
#define IDC_APPOPT_LANGUAGE_GRP         1032
#define IDS_MANAGELAYOUTS_LISTLABEL     1032
#define IDC_APPOPT_LANGUAGE_ICON        1033
#define IDS_MANAGEGLBOPS_CAPTION        1033
#define IDS_LAYOUTCFG_COLDESC           1033
#define IDS_MANAGEGLBOPS_LISTLABEL      1034
#define IDC_APPOPT_SAVELAYOUT           1034
#define IDS_CONFIGUREOPERATION          1035
#define IDS_CONFIGURETHISLAYOUT         1036
#define IDS_SWITCHTOTHISLAYOUT          1037
#define IDS_CONFIGURETHISOPERATION      1038
#define IDS_EXECUTETHISOPERATION        1039
#define IDS_LAYOUT_OPEN                 1040
#define IDS_LAYOUT_SAVE                 1041
#define IDS_LAYOUT_FILETYPE             1042
#define IDS_COMMAND_OPEN                1043
#define IDS_COMMAND_SAVE                1044
#define IDS_COMMAND_FILETYPE            1045
#define IDS_MENUCOMMANDS_FILEOPS        2048
#define IDS_MENUCOMMANDS_SAVEAS         2049
#define IDS_MENUCOMMANDS_CLOSE          2050
#define IDS_MENUCOMMANDS_EXIT           2051
#define IDS_MENUCOMMANDS_RECENT         2052
#define IDS_MENUCOMMANDS_BARS           2053
#define IDS_MENUCOMMANDS_STATUS         2053
#define IDS_MENUCOMMANDS_CLIPBOARD      2054
#define IDS_MENUCOMMANDS_UNDO           2055
#define IDS_MENUCOMMANDS_LAYOUTS        2056
#define IDS_MENUCOMMANDS_LAYOUTCFG      2057
#define IDS_MENUCOMMANDS_LAYOUTSMNG     2058
#define IDS_MENUCOMMANDS_OPTIONS        2059
#define IDS_MENUCOMMANDS_FRAMETOOLS     2060
#define IDS_MENUCOMMANDS_HELP           2061
#define IDS_MENUCOMMANDS_ASKONLINE      2062
#define IDS_MENUCOMMANDS_CONTEXT        2063
#define IDS_MENUCOMMANDS_ABOUT          2064
#define IDS_MENUCOMMANDS_SELECTALL      2065
#define IDS_MENUCOMMANDS_INVERTSELECTION 2066
#define IDS_MENUCOMMANDS_EXECCMD        2067
#define IDS_MENUCOMMANDS_CUSTOM         2068
#define IDS_MENUCOMMANDS_REDO           2069
#define IDS_MENUCOMMANDS_DELETE         2070
#define IDS_MENUCOMMANDS_DUPLICATE      2071
#define IDS_MN_FILE_NEW                 2080
#define IDS_MD_FILE_NEW                 2081
#define IDS_MN_FILE_OPEN                2082
#define IDS_MD_FILE_OPEN                2083
#define IDS_MN_FILE_SAVE                2084
#define IDS_MD_FILE_SAVE                2085
#define IDS_MN_FILE_SAVEAS              2086
#define IDS_MD_FILE_SAVEAS              2087
#define IDS_MN_FILE_CLOSE               2088
#define IDS_MD_FILE_CLOSE               2089
#define IDS_MN_FILE_EXIT                2090
#define IDS_MD_FILE_EXIT                2091
#define IDS_MN_FILE_RECENT              2092
#define IDS_MD_FILE_RECENT              2093
#define IDS_MN_HELP_CONTENTS            2094
#define IDS_MN_HELP_LOCAL               2094
#define IDS_MD_HELP_CONTENTS            2095
#define IDS_MD_HELP_LOCAL               2095
#define IDS_MN_HELP_INDEX               2096
#define IDS_MD_HELP_INDEX               2097
#define IDS_MN_HELP_SEARCH              2098
#define IDS_MD_HELP_SEARCH              2099
#define IDS_MN_HELP_ASKONLINE           2100
#define IDS_MD_HELP_ASKONLINE           2101
#define IDS_MN_HELP_CONTEXT             2102
#define IDS_MD_HELP_CONTEXT             2103
#define IDS_MN_HELP_ABOUT               2104
#define IDS_MD_HELP_ABOUT               2105
#define IDS_MN_EDIT_UNDO                2112
#define IDS_MD_EDIT_UNDO                2113
#define IDS_MN_VIEW_STATUS              2114
#define IDS_MD_VIEW_STATUS              2115
#define IDS_MN_VIEW_TOOLBAR             2116
#define IDS_MD_VIEW_TOOLBAR             2117
#define IDS_MN_VIEW_OPERATIONS          2118
#define IDS_MD_VIEW_OPERATIONS          2119
#define IDS_MN_VIEW_LAYOUTCFG           2120
#define IDS_MD_VIEW_LAYOUTCFG           2121
#define IDS_MN_TOOLS_LAYOUTMNG          2122
#define IDS_MD_TOOLS_LAYOUTMNG          2123
#define IDS_MN_TOOLS_OPTIONS            2124
#define IDS_MD_TOOLS_OPTIONS            2125
#define IDS_MN_VIEW_SWITCHLAYOUT        2126
#define IDS_MD_VIEW_SWITCHLAYOUT        2127
#define IDS_MN_HELP_CUSTOM              2128
#define IDS_MD_HELP_CUSTOM              2129
#define IDS_MN_EDIT_REDO                2130
#define IDS_MD_EDIT_REDO                2131
#define IDS_HELP_IDOK                   16384
#define IDS_HELP_IDCANCEL               16385
#define IDS_HELP_IDHELP                 16386
#define IDS_HELP_MNGOPS_LIST            16387
#define IDS_HELP_MANAGE_LAYOUTLIST      16387
#define IDS_HELP_MNGOPS_TOOLBAR         16388
#define IDS_HELP_MANAGE_TOOLBAR         16388
#define IDS_HELP_APPOPT_LANGUAGE        16389
#define IDS_CONTEXTHELP_TOOLBAR         16390
#define IDS_HELP_APPOPT_ASKTOSAVE       16391
#define IDS_HELP_APPOPT_SHOWTUTORIAL    16392
#define IDS_HELP_APPOPT_STARTPAGE       16392
#define IDS_HELP_MANAGE_GLBOPSLIST      16393
#define IDS_HELP_APPOPT_UNDODEFAULT     16394
#define IDS_HELP_APPOPT_UNDODISABLED    16395
#define IDS_HELP_APPOPT_UNDOSINGLE      16396
#define IDS_HELP_APPOPT_UNDOMULTIPLE    16397
#define IDS_HELP_APPOPT_UNDOALL         16398
#define IDS_HELP_APPOPT_SAVELAYOUT      16399
#define IDS_CONTEXTHELP_REBAR           16400
#define IDS_CONTEXTHELP_MENUBAR         16401
#define IDS_CONTEXTHELP_STATUSBAR       16402
#define IDS_CONTEXTHELP_NONE            16404
#define ATL_IDS_IDLEMESSAGE             0xE001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        259
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         283
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
