
#pragma once

#include <ConfigCustomGUIIcons.h>
#include <ConfigCustomGUIML.h>

class ATL_NO_VTABLE CConfigGUIShowTransformationConfigDlg :
	public CCustomConfigWndMultiLang<CConfigGUIShowTransformationConfigDlg, CCustomConfigWndWithIcons<CConfigGUIShowTransformationConfigDlg> >,
	public CDialogResize<CConfigGUIShowTransformationConfigDlg>
{
public:
	CConfigGUIShowTransformationConfigDlg() :
		CCustomConfigWndMultiLang<CConfigGUIShowTransformationConfigDlg, CCustomConfigWndWithIcons<CConfigGUIShowTransformationConfigDlg> >(CFGID_CFG_CAPTION, CFGID_CFG_HELPTOPIC)
	{
	}

	enum { IDD = IDD_CONFIGGUI_TRANSITEM };

	BEGIN_MSG_MAP(CConfigGUIShowTransformationConfigDlg)
		CHAIN_MSG_MAP(CDialogResize<CConfigGUIShowTransformationConfigDlg>)
		CHAIN_MSG_MAP(CCustomConfigWndWithIcons<CConfigGUIShowTransformationConfigDlg>)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
	END_MSG_MAP()

	BEGIN_DLGRESIZE_MAP(CConfigGUIShowTransformationConfigDlg)
		DLGRESIZE_CONTROL(IDC_CG_CAPTION, DLSZ_SIZE_X)
		DLGRESIZE_CONTROL(IDC_CG_ICONLABEL, DLSZ_MOVE_X)
		DLGRESIZE_CONTROL(IDC_CG_ICON, DLSZ_MOVE_X)
		DLGRESIZE_CONTROL(IDC_CG_OPERATION, DLSZ_DIVSIZE_X(2))
		DLGRESIZE_CONTROL(IDC_CG_OPCONFIG, DLSZ_DIVSIZE_X(2)|DLSZ_SIZE_Y)
		DLGRESIZE_CONTROL(IDC_CG_PREVIEWLABEL, DLSZ_DIVMOVE_X(2))
		DLGRESIZE_CONTROL(IDC_CG_PREVIEW, DLSZ_DIVMOVE_X(2)|DLSZ_DIVSIZE_X(2))
		DLGRESIZE_CONTROL(IDC_CG_VIEWCONFIG, DLSZ_DIVMOVE_X(2)|DLSZ_DIVSIZE_X(2)|DLSZ_SIZE_Y)
		DLGRESIZE_CONTROL(IDC_CG_HELPTOPIC_LABEL, DLSZ_MOVE_Y)
		DLGRESIZE_CONTROL(IDC_CG_HELPTOPIC, DLSZ_MOVE_Y|DLSZ_SIZE_X)
	END_DLGRESIZE_MAP()

	BEGIN_CONFIGITEM_MAP(CConfigGUIShowTransformationConfigDlg)
		CONFIGITEM_EDITBOX(IDC_CG_CAPTION, CFGID_CFG_CAPTION)
		CONFIGITEM_ICONCOMBO(IDC_CG_ICON, CFGID_CFG_ICONID)
		CONFIGITEM_COMBOBOX(IDC_CG_OPERATION, CFGID_CFG_TRANSFORMATION)
		CONFIGITEM_SUBCONFIG(IDC_CG_OPCONFIG, CFGID_CFG_TRANSFORMATION)
		CONFIGITEM_COMBOBOX(IDC_CG_PREVIEW, CFGID_CFG_PREVIEW)
		CONFIGITEM_SUBCONFIG(IDC_CG_VIEWCONFIG, CFGID_CFG_PREVIEW)
		CONFIGITEM_EDITBOX(IDC_CG_HELPTOPIC, CFGID_CFG_HELPTOPIC)
	END_CONFIGITEM_MAP()

	LRESULT OnInitDialog(UINT UNREF(a_uMsg), WPARAM UNREF(a_wParam), LPARAM UNREF(a_lParam), BOOL& a_bHandled)
	{
		DlgResize_Init(false, false, 0);

		return 1;
	}
};

