
#pragma once

#include <ConfigCustomGUIIcons.h>

class ATL_NO_VTABLE CConfigGUIPopupDlg :
	public CCustomConfigWndWithIcons<CConfigGUIPopupDlg>,
	public CDialogResize<CConfigGUIPopupDlg>
{
public:
	enum { IDD = IDD_CONFIGGUI_POPUP };

	BEGIN_MSG_MAP(CConfigGUIPopupDlg)
		CHAIN_MSG_MAP(CDialogResize<CConfigGUIPopupDlg>)
		CHAIN_MSG_MAP(CCustomConfigWndImpl<CConfigGUIPopupDlg>)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
	END_MSG_MAP()

	BEGIN_DLGRESIZE_MAP(CConfigGUIPopupDlg)
		DLGRESIZE_CONTROL(IDC_CG_NAME, DLSZ_SIZE_X)
		DLGRESIZE_CONTROL(IDC_CG_ICONLABEL, DLSZ_MOVE_X)
		DLGRESIZE_CONTROL(IDC_CG_ICON, DLSZ_MOVE_X)
		DLGRESIZE_CONTROL(IDC_CG_DESCRIPTION, DLSZ_SIZE_X)
		DLGRESIZE_CONTROL(IDC_CG_OPERATION, DLSZ_SIZE_X)
		DLGRESIZE_CONTROL(IDC_CG_OPCONFIG, DLSZ_SIZE_X|DLSZ_SIZE_Y)
	END_DLGRESIZE_MAP()

	BEGIN_CONFIGITEM_MAP(CConfigGUIPopupDlg)
		CONFIGITEM_EDITBOX(IDC_CG_NAME, CFGID_POPUP_NAME)
		CONFIGITEM_EDITBOX(IDC_CG_DESCRIPTION, CFGID_POPUP_DESCRITPION)
		CONFIGITEM_COMBOBOX(IDC_CG_OPERATION, CFGID_POPUP_SUBCOMMANDS)
		CONFIGITEM_ICONCOMBO(IDC_CG_ICON, CFGID_POPUP_ICONID)
		CONFIGITEM_CHECKBOX(IDC_CG_ICONFROMRADIO, CFGID_POPUP_ICONFROMRADIO)
		CONFIGITEM_CHECKBOX(IDC_CG_TEXTINTOOLBAR, CFGID_POPUP_TEXTINTOOLBAR)
		CONFIGITEM_SUBCONFIG(IDC_CG_OPCONFIG, CFGID_POPUP_SUBCOMMANDS)
	END_CONFIGITEM_MAP()

	LRESULT OnInitDialog(UINT UNREF(a_uMsg), WPARAM UNREF(a_wParam), LPARAM UNREF(a_lParam), BOOL& a_bHandled)
	{
		DlgResize_Init(false, false, 0);

		return 1;
	}
};
