
#pragma once

#include <ConfigCustomGUIImpl.h>

class ATL_NO_VTABLE CConfigGUIPipeDlg :
	public CCustomConfigWndImpl<CConfigGUIPipeDlg>,
	public CDialogResize<CConfigGUIPipeDlg>
{
public:
	enum { IDD = IDD_CONFIGGUI_PIPE };

	BEGIN_MSG_MAP(CConfigGUIPipeDlg)
		CHAIN_MSG_MAP(CDialogResize<CConfigGUIPipeDlg>)
		CHAIN_MSG_MAP(CCustomConfigWndImpl<CConfigGUIPipeDlg>)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
	END_MSG_MAP()

	BEGIN_DLGRESIZE_MAP(CConfigGUIPipeDlg)
		DLGRESIZE_CONTROL(IDC_CGP_TRANSFORMATION, DLSZ_SIZE_X)
		DLGRESIZE_CONTROL(IDC_CGP_TRANSCONFIG, DLSZ_SIZE_X|DLSZ_DIVSIZE_Y(2))
		DLGRESIZE_CONTROL(IDC_CGP_OPERATION, DLSZ_SIZE_X|DLSZ_DIVMOVE_Y(2))
		DLGRESIZE_CONTROL(IDC_CGP_OPLABEL, DLSZ_DIVMOVE_Y(2))
		DLGRESIZE_CONTROL(IDC_CGP_OPCONFIG, DLSZ_SIZE_X|DLSZ_DIVMOVE_Y(2)|DLSZ_DIVSIZE_Y(2))
	END_DLGRESIZE_MAP()

	BEGIN_CONFIGITEM_MAP(CConfigGUIPipeDlg)
		CONFIGITEM_COMBOBOX(IDC_CGP_TRANSFORMATION, CFGID_PIPE_TRANSFORMATION)
		CONFIGITEM_COMBOBOX(IDC_CGP_OPERATION, CFGID_PIPE_OPERATION)
		CONFIGITEM_SUBCONFIG(IDC_CGP_TRANSCONFIG, CFGID_PIPE_TRANSFORMATION)
		CONFIGITEM_SUBCONFIG(IDC_CGP_OPCONFIG, CFGID_PIPE_OPERATION)
	END_CONFIGITEM_MAP()

	LRESULT OnInitDialog(UINT UNREF(a_uMsg), WPARAM UNREF(a_wParam), LPARAM UNREF(a_lParam), BOOL& a_bHandled)
	{
		DlgResize_Init(false, false, 0);

		return 1;
	}
};
