//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RWProcessing.rc
//
#define IDS_PROJNAME                    100
#define IDR_MOUSEGESTURESHELPER         122
#define IDR_DEFAULTGESTURES             123
#define IDS_TRANFORMATIONNULL_NAME      128
#define IDS_OPERATIONNULL_NAME          129
#define IDS_OPERATIONPIPE_NAME          130
#define IDS_OPERATIONSPLIT_NAME         131
#define IDS_MENUCOMMANDSVECTOR_NAME     132
#define IDS_MENUCOMMANDSPOPUP_NAME      133
#define IDS_MENUCOMMANDSOPERATION_NAME  134
#define IDS_MENUCOMMANDSSEPARATOR_NAME  135
#define IDS_PIPE_TRANSFORMATION_NAME    136
#define IDS_PIPE_TRANSFORMATION_DESC    137
#define IDS_PIPE_OPERATION_NAME         138
#define IDS_PIPE_OPERATION_DESC         139
#define IDS_SPLIT_OPERATION1_NAME       140
#define IDS_SPLIT_OPERATION1_DESC       141
#define IDS_SPLIT_OPERATION2_NAME       142
#define IDS_SPLIT_OPERATION2_DESC       143
#define IDS_CFGID_VECTOR_SUBCOMMANDS_NAME 144
#define IDS_CFGID_VECTOR_SUBCOMMANDS_DESC 145
#define IDS_CFGID_VECTOR_ITEMS_NAME     146
#define IDS_CFGID_VECTOR_ITEMS_DESC     147
#define IDS_CFGID_POPUP_SUBCOMMANDS_NAME 148
#define IDS_CFGID_POPUP_SUBCOMMANDS_DESC 149
#define IDS_CFGID_NAME_NAME             150
#define IDS_CFGID_NAME_DESC             151
#define IDS_CFGID_DESCRITPION_NAME      152
#define IDS_CFGID_DESCRITPION_DESC      153
#define IDS_CFGID_ICONID_NAME           154
#define IDS_CFGID_ICONID_DESC           155
#define IDS_CFGID_OPERATION_ID_NAME     156
#define IDS_CFGID_OPERATION_ID_DESC     157
#define IDS_SHOWCONFIG                  158
#define IDS_CFGID_POPUP_ICONFROMRADIO_NAME 159
#define IDS_CFGID_POPUP_ICONFROMRADIO_DESC 160
#define IDS_CFGID_POPUP_TEXTINTOOLBAR_NAME 161
#define IDS_CFGID_POPUP_TEXTINTOOLBAR_DESC 162
#define IDS_CFGID_OPERATION_RUNTIMECONFIG_NAME 163
#define IDS_CFGID_OPERATION_RUNTIMECONFIG_DESC 164
#define IDS_LISTBUTTONNAMES             165
#define IDS_RWCOMMANDS_OPEN             166
#define IDS_RWCOMMANDS_SAVE             167
#define IDS_RWCOMMANDS_FILTER           168
#define IDS_CFG_DLGSIZEX                169
#define IDS_CFG_DLGSIZEY                170
#define IDS_CFG_CAPTION_NAME            171
#define IDS_CFG_PREVIEW_NAME            172
#define IDS_CFG_PREVIEW_DESC            173
#define IDS_CFG_CAPTION_DESC            174
#define IDS_CFGID_ICONID_DESC2          175
#define IDS_CFGID_ICONID_NAME2          176
#define IDS_CFG_AUTOUPDATE              177
#define IDS_CFG_HELPTOPIC_NAME          178
#define IDS_CFG_HELPTOPIC_DESC          179
#define IDS_1DINTERACTIVECONFIG         180
#define IDS_CFG_PARAMETER_NAME          181
#define IDS_CFG_PARAMETER_DESC          182
#define IDS_CFG_PARLOWER_NAME           183
#define IDS_CFG_PARLOWER_DESC           184
#define IDS_CFG_PARUPPER_NAME           185
#define IDS_CFG_PARUPPER_DESC           186
#define IDS_CFG_PARSCALE_NAME           187
#define IDS_CFG_PARSCALE_DESC           188
#define IDS_CFGVAL_LINEAR               189
#define IDS_CFGVAL_LOGARITHMIC          190
#define IDS_CFGID_SHORTCUT_NAME         191
#define IDS_CFGID_SHORTCUT_DESC         192
#define IDS_NOSHORTCUT                  193
#define IDS_BTN_CANCEL                  194
#define IDS_BTN_SKIP                    195
#define IDS_CFGID_SEQ_STEPS_NAME        196
#define IDS_CFGID_SEQ_STEPS_DESC        197
#define IDS_CFGID_SEQ_TYPE_NAME         198
#define IDS_CFGID_SEQ_TYPE_DESC         199
#define IDS_CFGID_SEQ_OPERATION_NAME    200
#define IDS_CFGID_SEQ_OPERATION_DESC    201
#define IDC_COMBO2                      202
#define IDC_CGS_OPERATION               202
#define IDS_CFGID_SEQ_TRANSFORMATION_NAME 202
#define IDC_CG_PARAM1SCALE              202
#define IDC_CGS_TRANSFORMATION          203
#define IDS_CFGID_SEQ_TRANSFORMATION_DESC 203
#define IDS_OPERATIONSEQUENCE_NAME      204
#define IDD_CONFIGGUI_OPERATION         205
#define IDI_MOVEUP                      205
#define IDS_SEQBUTTONNAMES              205
#define IDC_CG_NAME                     206
#define IDD_CONFIGGUI_POPUP             206
#define IDI_MOVEDOWN                    206
#define IDS_JSCRIPT_NAME                206
#define IDC_CG_DESCRIPTION              207
#define IDS_CFGID_JS_SCRIPT_NAME        207
#define IDS_CFGID_JS_SCRIPT_DESC        208
#define IDC_CG_OPERATION                209
#define IDS_CFGID_CFG_DISPLAYMODE_NAME  209
#define IDC_CG_OPCONFIG                 210
#define IDD_CONFIGGUI_SEQUENCE          210
#define IDS_CFGID_CFG_DISPLAYMODE_DESC  210
#define IDC_CG_TEXTINTOOLBAR            211
#define IDC_CG_VIEWCONFIG               211
#define IDS_CFGID_CFGVAL_DM_ORIGINAL    211
#define IDC_CG_ICONFROMRADIO            212
#define IDS_CFGID_CFGVAL_DM_PROCESSED   212
#define IDS_CFGVAL_DM_BOTH              213
#define IDC_CG_TOOLBAR                  214
#define IDS_PREVIEWTOOLBAR              214
#define IDC_CG_LIST                     215
#define IDS_CFGID_JS_CFGSCRIPT_NAME     215
#define IDD_DIALOG1                     215
#define IDD_CONFIGGUI_SCRIPTPANEL       215
#define IDC_CG_ITEM                     216
#define IDS_CFGID_JS_CFGSCRIPT_DESC     216
#define IDC_CG_ICONLABEL                217
#define IDS_CUSTCFG_MORECOLORS          217
#define IDC_RT_SAVECHANGES              218
#define IDC_CG_ICON                     218
#define IDI_PREVIEW_ORIGINAL4           218
#define IDS_CUSTCFG_COLORNAMES          218
#define IDS_CUSTCFG_FROMPIXEL           219
#define IDS_MENUCOMMANDSAUTOOPERATION_NAME 220
#define IDS_CFGID_OPERATION_CLASS_NAME  221
#define IDS_CFGID_OPERATION_CLASS_DESC  222
#define IDC_CG_CAPTION                  223
#define IDC_CG_PREVIEW                  224
#define IDC_CG_PREVIEWLABEL             225
#define IDC_CG_HELPTOPIC                232
#define IDC_CG_HELPTOPIC_LABEL          233
#define IDC_1DRT_SLIDER                 236
#define IDC_1DRT_EDIT                   237
#define IDC_1DRT_PARAMETER              244
#define IDC_CG_SHORTCUT                 246
#define IDC_CG_SHORTCUTLABEL            247
#define IDC_CGS_TYPE                    248
#define IDC_CGS_OPCONFIG                249
#define IDC_CGS_TRCONFIG                250
#define IDC_CG_PARAM1NAME               251
#define IDD_CONFIGGUI_VECTOR            254
#define IDD_CONFIGGUI_VECTORITEM        255
#define IDD_CONFIGGUI_OPITEM            256
#define IDD_CONFIGGUI_TRANSITEM         257
#define IDC_CG_PARAM1MIN                258
#define IDD_CONFIGGUI_STEP              259
#define IDC_CG_PARAM1MAX                259
#define IDC_CG_PARAM1LABEL              260
#define IDC_CG_PARAM1BOUNDS             261
#define IDD_CONFIGGUI_SLIDER            261
#define IDD_CONFIGUREGESTURES           274
#define IDC_CG_HISTORY                  275
#define IDC_CG_PREVIEWMODE              276
#define IDC_CG_PREVIEWMODE_LABEL        277
#define IDC_MG_GESTURES                 304
#define IDC_MG_OPERATION                305
#define IDC_MG_LABEL                    306
#define IDC_MG_CONFIG                   307
#define IDS_HELP_IDOK                   16384
#define IDS_HELP_IDCANCEL               16385
#define IDS_HELP_IDHELP                 16386
#define IDS_HELP_RT_SAVECHANGES         16387
#define IDS_HELP_RT_UPDATE              16388
#define IDS_HELP_RT_TOOLBAR             16388
#define IDS_HELP_RT_AUTO                16389
#define IDS_HELP_IDSKIP                 16390

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        216
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         278
#define _APS_NEXT_SYMED_VALUE           124
#endif
#endif
